language: python
sudo: false
python:
  - "3.6"
cache:
  directories:
    - $HOME/.env/pip
script:
  - python --version
  - pip install virtualenv
  - virtualenv .env
  - source .env/bin/activate
  - pip install -r requirements.txt
  - pip freeze
